version: '3'
services:
  framework-mg:
    container_name: framework-mg
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "18080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:8080" ]
      interval: 60s
      timeout: 3s
      retries: 3
    environment:
      BASE_DIR: '/framework'
      TZ: Asia/Shanghai
    volumes:
      - ./framework:/framework
      - ./logs:/app/logs
    cpus: "1"
    mem_limit: 256M